### ISSUE TITLE
The "CreateJson" function in the "JsonArrayParser" class does not work correctly.

### ISSUE THREAD

**Issue by rinat9177** [tomasfabian/ksqlDB.RestApi.Client-DotNet#31]
**Describe the bug**
When I try to get a field from the ksqlDb that contains a quote, I get an error:
System.Text.Json.JsonException: '}' is invalid after a property name. Expected a ':'. Path: $ | LineNumber: 5 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '}' is invalid after a property name. Expected a ':'. LineNumber: 5 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumePropertyName()
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at ksqlDB.RestApi.Client.KSql.RestApi.Query.KSqlDbQueryProvider.CreateRowValue[T](String rawJson)
   at ksqlDB.RestApi.Client.KSql.RestApi.Query.KSqlDbQueryProvider.OnLineRead[T](String rawJson)
   at ksqlDB.RestApi.Client.KSql.RestApi.KSqlDbProvider.ConsumeAsync[T](StreamReader streamReader, SemaphoreSlim semaphoreSlim, CancellationToken cancellationToken)+MoveNext()
   at ksqlDB.RestApi.Client.KSql.RestApi.KSqlDbProvider.ConsumeAsync[T](StreamReader streamReader, SemaphoreSlim semaphoreSlim, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at ksqlDB.RestApi.Client.KSql.RestApi.KSqlDbProvider.Run[T](Object parameters, CancellationToken cancellationToken)+MoveNext()
   at ksqlDB.RestApi.Client.KSql.RestApi.KSqlDbProvider.Run[T](Object parameters, CancellationToken cancellationToken)+MoveNext()
   at ksqlDB.RestApi.Client.KSql.RestApi.KSqlDbProvider.Run[T](Object parameters, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()

**To Reproduce**
1. JSON:
{
	 "data": "{\"internalId\":\"7775dee282f011724d3108f25302b996\",\"fileName\":\"test.json\",\"result\":{\"type\":\"Monitor\",\"name\":\"27\\u0022 XZ272UVBMIIPHX Black\",\"error\":\"\"}}",
  "datacontenttype": "application/json",
  "id": "87df3d0c19024d5f8c04a3649c666506"
}
2. CREATE STREAM BASE_STREAM (
          data VARCHAR)
 WITH (KAFKA_TOPIC='base_topic',
       VALUE_FORMAT='JSON',
       PARTITIONS=1);
3. CREATE STREAM IF NOT EXISTS RESULT_STREAM AS
                    SELECT
                    EXTRACTJSONFIELD(DATA, '$.internalId') as internalId,
                    EXTRACTJSONFIELD(DATA, '$.fileName') as fileName,
					EXTRACTJSONFIELD(DATA, '$.result.type') as type,
					EXTRACTJSONFIELD(DATA, '$.result.name') as name,
                    EXTRACTJSONFIELD(DATA, '$.result.error') as error
                    FROM
                        BASE_STREAM;
4. CREATE TABLE IF NOT EXISTS RESULT_TABLE
                    WITH (kafka_topic='RESULT_TABLE', FORMAT='JSON') AS
                    SELECT internalId,
					EARLIEST_BY_OFFSET(fileName) AS fileName,
					LATEST_BY_OFFSET(type) AS type,
					LATEST_BY_OFFSET(name) AS name,
					LATEST_BY_OFFSET(error) AS error
                    FROM RESULT_STREAM
                    GROUP BY internalId;
5.  public ValueTask<Result?> GetResultById(string id)
    {
        return _context.Results
            .Where(i => i.InternalId == id)
            .Take(ItemsLimit)
            .GetManyAsync()
            .FirstOrDefaultAsync();
    }

**Expected behavior**
Get row from ksqlDb

**Environment (please complete the following information):**
 - ksqldb version: 0.27.2
 - ksqlDB.RestApi.Client 2.3.1

**Comment by tomasfabian** [comment]
Hi @rinat9177, 
I published a hot fix for your issue:

```
Install-Package ksqlDb.RestApi.Client -Version 2.3.2
```

Regards Tomas.
